#!/bin/bash
# save/restore FWLive config to/from a file
# $1 = full path to new fwliveconf.mo file

TEXTDOMAIN=fwlive
TEXTDOMAINDIR=/usr/share/locale

PATH=$PATH:/usr/sbin

# only root can run this
if [ "0$UID" -ne 0 ]; then
	printf $"Only root can run %s.\n" "`basename $0`"; exit 1
fi

. /usr/local/bin/liblinuxlive

FWCONF=fwliveconf.lzm
MEMORY=/$MOUNTDIR/live/memory
CHANGES=$MEMORY/changes
SAVEDIRS=" @SAVE_DIRS@"

CONFFILE=$1
if [ "$CONFFILE" = "" ]; then printf $"usage: %s /media/sda?/%s\n" $0 $FWCONF; exit 1; fi
if [ -e "$CONFFILE" -a ! -f "$CONFFILE" ]; then printf $"Not a regular file: %s\n" $CONFFILE; exit 1; fi

# directory with changes is only in FWLive, not in installed version
if [ ! -d $CHANGES ]; then
	echo $"This script can work only from FWLive."; exit 1
fi

# INIT
# ***********************

MYSELF="`basename \"$0\"`"

# SAVE
# ***********************

if [ "$MYSELF" = "configsave" ]; then
	printf $"Saving changes to %s... " $CONFFILE
	rm $CONFFILE 2>/dev/null
	touch ${SAVEDIRS// / $CHANGES/}
	mksquashfs ${SAVEDIRS// / $CHANGES/} $CONFFILE -e $CHANGES/var/{run,log,man,tmp} /etc/fstab >/dev/null 2>/dev/null
	if [ $? -ne 0 ]; then
		printf $"Can't write config to %s\n" $CONFFILE; exit 1
	else
		echo $"done."
	fi
fi

# RESTORE
# ***********************

if [ "$MYSELF" = "configrestore" ]; then
	printf $"Restoring changes from %s... " $CONFFILE
	lzm2dir $CONFFILE $CHANGES
	uniondbg -g /
	echo $"done."
fi
