#!/bin/sh

# mountpoint dectector v0.3 for FwLive
# created by Krisztian VASAS <iron@frugalware.org>

dn=0
rn=0

_cp=`which cp`
_ln=`which ln`
_ls=`which ls`
_mv=`which mv`
_tr=`which tr`
_awk=`which awk`
_cat=`which cat`
_cut=`which cut`
_sed=`which sed`
_expr=`which expr`
_grep=`which grep`
_fdisk=`which fdisk`
_mkdir=`which mkdir`
_parted=`which parted`

rootfs=`$_cat /proc/cmdline | sed 's/.* root=\/dev\/\(.*\).*/\1/'|cut -d ' ' -f 1`
[ -f /tmp/fstab ] && rm /tmp/fstab

echo "tmpfs  /        tmpfs  defaults        0 0 # Auto-Update" >> /tmp/fstab
echo "devpts /dev/pts devpts gid=5,mode=620  0 0 # Auto-Update" >> /tmp/fstab
echo "none  /proc  proc  defaults  0  0" >> /tmp/fstab
echo "none  /sys   sysfs defaults  0  0" >> /tmp/fstab

echo -n "Creating /etc/fstab"
for dev in `$_ls -1 /sys/block | $_grep -v ^md | $_grep -v ^ram | $_grep -v ^loop`; do
#	Found device let's see what is this...
	dev=`echo $dev | $_sed 's|/||'`
	if [ `$_cat /sys/block/$dev/removable` -eq 0 ]; then
		if [ -f /sys/block/$dev/device/model ]; then
			mntpoint=disk${dn}-`$_cat /sys/block/$dev/device/model | $_sed 's/ *$//;s/^ *//; s/\W/-/g; s/\ /-/g'`
		else
			mntpoint=disk${dn}_`$_cat /proc/ide/$dev/model | $_tr ' ' '_'`
		fi
#		This is a disk, looking for partitions...
		for j in `$_ls /sys/block/$dev/ | $_grep $dev`; do
			j=`echo $j | $_sed 's|/||'`
			p=`echo $j | $_sed "s|$dev||"`
			part=part$p
			partid=`$_fdisk -l /dev/$dev| $_grep ^/dev/$j | $_cut -b53-54`
			fs=`$_parted /dev/$dev print | $_grep ^$p | $_awk '{print $6}'`
			[ $rootfs != $j ] && case $fs in
				ext3)
					fstype='ext3'
					$_mkdir -p /mnt/$mntpoint/$part
					echo "/dev/$j  /mnt/$mntpoint/$part  $fstype  defaults  0  0" >> /tmp/fstab
				;;
				linux-swap)
# don't put anything here, we don't need currently swap
# or maybe yes?
					fstype='swap'
					echo "/dev/$j  swap  $fstype  defaults  0  0" >> /tmp/fstab
				;;
				fat32)
					fstype='vfat'
					$_mkdir -p /mnt/$mntpoint/$part
					echo "/dev/$j  /mnt/$mntpoint/$part  $fstype  defaults,umask=022,showexec,shortname=winnt  0  0" >> /tmp/fstab
				;;
				*)
					ptype=`$_parted /dev/$dev print | $_grep ^$p | $_awk '{print $5}'`
					if [ "$ptype" != "extended" ]; then
						if [ "$fs" != "" ]; then
							fstype=$fs
							$_mkdir -p /mnt/$mntpoint/$part
							echo "/dev/$j  /mnt/$mntpoint/$part  $fstype  defaults  0  0" >> /tmp/fstab
						fi
					fi
				;;
			esac

		done
		dn=`$_expr $dn + 1`
	else
		case $dev in
			fd0)
				# This is a floppy...
				$_mkdir -p /media/floppy
				echo "/dev/$dev   /media/floppy  auto  user,noauto,noexec  0  0" >> /tmp/fstab
			;;
			*)
				# This is a CD/DVD drive...
				bootdev=`cat /tmp/bootcd | sed 's|/dev/||'`
				mntpoint=cdrom${rn}_`$_cat /proc/ide/$dev/model | $_sed 's/ *$//; s/^ *//; s/\W/-/g; s/\ /-/g'`
				rn=`$_expr $rn + 1`
				if [ "$bootdev" == "$dev" ]; then
					$_ln -s /mnt/live/mnt/$dev /media/$mntpoint
					$_ln -s /media/$mntpoint /cdrom
					$_ln -s /dev/$dev /dev/cdrom
				else
					$_mkdir -p /media/$mntpoint
				fi
				echo "/dev/$dev   /media/$mntpoint  auto  ro,noauto,user  0  0" >> /tmp/fstab
			;;
		esac
fi
done

$_cp /tmp/fstab /etc/fstab

echo " - done."
