#!/bin/bash
# Create an empty file in /mnt and activate it as a swap
# Author: Tomas M <http://slax.linux-live.org>
#

TEXTDOMAIN=fwlive
TEXTDOMAINDIR=/usr/share/locale

# only root can run this
if [ "0$UID" -ne 0 ]; then
   printf $"Only root can run %s.\n" "`basename $0`"; exit 1
fi

SWAPFILE=$1
SWAPSIZE=$2

if [ $(($SWAPSIZE)) -lt 1 ]; then
   echo $"File Swap - create swap as a file in writable filesystem" >&2
   printf $"usage: %s [/media/partition/new_name.swap] [size MB]\n" $0>&2
   exit 1
fi

if [ -d "$SWAPFILE" ]; then
   printf "%s is a directory, use %s/fwswap.swp instead\n" $SWAPFILE $SWAPFILE>&2
   exit 1
fi

if [ "`echo \"$SWAPFILE\" | egrep \"^/media\"`" = "" ]; then
   echo $"you must use path in /media" >&2
   exit 1
fi

printf $"creating empty %s\n" $SWAPFILE
dd if=/dev/zero of=$SWAPFILE count=$SWAPSIZE bs=1M
if [ "$?" -ne 0 ]; then exit 1; fi

printf $"setting up Linux swap area on %s\n" $SWAPFILE
mkswap $SWAPFILE >/dev/null
if [ "$?" -ne 0 ]; then exit 1; fi

printf $"activating swap on %s\n" $SWAPFILE
swapon $SWAPFILE
if [ "$?" -ne 0 ]; then exit 1; fi
