#!/bin/sh

# (c) 2007 Miklos Vajna <vmiklos@frugalware.org>
# (c) 2008 Janos Kovacs <janny@frugalware.org>
# parse_cmdline for Frugalware
# distributed under GPL License

. /usr/local/bin/liblinuxlive

# change password
NEWROOTPASS="`cmdline_value passwd`"
if [ "$NEWROOTPASS" = "ask" ]; then
        echo -ne "\nEnter new password for root: "
        read -s NEWROOTPASS
fi

if [ ! "$NEWROOTPASS" = "" ]; then
        echo "root:$NEWROOTPASS" | /usr/sbin/chpasswd
fi

# debug
#if grep debug /proc/cmdline 2>/dev/null >/dev/null; then
#       show_debug_banner
#       /mnt/live/bin/ash || /bin/bash || /bin/sh
#fi

# if autoexec= boot parameter is present, automatically start the command given.
# If you need to execute several commands, separate them using ';'
# If you need to use spaces in your command, use ~ instead
# If you wish to reboot/poweroff after the command's execution is finished,
#  simply use autoexec=yourCommand;poweroff for example.
AUTOCMD=$(cmdline_value "autoexec" | tr "~" " ")
if [ "$AUTOCMD" != "" ]; then
        echo "starting autoexec command:  su --login -c \"$AUTOCMD\""
        su --login -c "$AUTOCMD"
fi
