#!/bin/sh

# /proc/cmdline parser v0.1 for FwLive
# created by Krisztian VASAS <iron@frugalware.org>

## get the paths dinamically
_tr=`which tr`
_cat=`which cat`
_cut=`which cut`

## default settings
cmdline=`$_cat /proc/cmdline`
mode="normal"
lang="hu_HU"

if [ "$mode" == "normal" ]; then
	case $lang in
		en_*)
			keymap=us
		;;
		*)
			keymap=`echo $lang | $_cut -b 1-2`
		;;
	esac
	cat << EOF > /etc/sysconfig/keymap 
# /etc/sysconfig/keymap

keymap=$keymap
EOF
	echo "export LANG=$lang" > /etc/profile.d/lang.sh
	echo "export LC_ALL=$lang" >> /etc/profile.d/lang.sh
	echo "export CHARSET=iso-8859-2" >> /etc/profile.d/lang.sh
	export LC_ALL=$lang
else
	echo ""
	/bin/bash
	reboot
#	This is the rescue mode, now just for support for latter versions...
fi
