#pragma once

#define _(S) S

#define OK_BUTTON_TEXT _("Ok")
#define CANCEL_BUTTON_TEXT _("Cancel")
#define YES_BUTTON_TEXT _("Yes")
#define NO_BUTTON_TEXT _("No")
#define PREVIOUS_BUTTON_TEXT _("Previous")
#define NEXT_BUTTON_TEXT _("Next")
#define PASSWORD_ENTER_TEXT _("Enter Password")
#define PASSWORD_CONFIRM_TEXT _("Confirm Password")
#define PASSWORD_LENGTH 6
#define PASSWORD_SHORT_TITLE _("Password Too Short")
#define PASSWORD_SHORT_TEXT _("Your password must be at least 6 characters long.\n")
#define PASSWORD_MISMATCH_TITLE _("Passwords Do Not Match")
#define PASSWORD_MISMATCH_TEXT _("The passwords you have entered do not match.\n")
#define FORMAT_TITLE _("Device Setup")
#define FORMAT_TEXT _("Select a device to setup from the list below.\n")
#define FORMAT_DIALOG_TITLE _("Filesystem Setup")
#define FORMAT_DIALOG_TEXT _("Please select mount path, parameters, and filesystem.\nMount path is optional if 'swap' is the selected filesystem.\nParameters are custom arguments passed to the format program.\nSelect 'noformat' if you wish to reuse the existing filesystem.\n")
#define FORMAT_PATH_TITLE _("Invalid Filesystem Parameters")
#define FORMAT_PATH_TEXT _("You have specified invalid parameters.\nPlease check that they meet the following requirements:\n\nMount path must begin with a '/'.\nMount path may only contain one directory.\nMount path must not already be in use.\n'noformat' cannot be chosen if there is no existing filesystem.\n")
#define FORMAT_MOUNT_ENTRY_TEXT _("Mount Path")
#define FORMAT_PARAMETERS_ENTRY_TEXT _("Format Parameters")
#define INSTALL_TITLE _("Package Group Selection")
#define INSTALL_TEXT _("Select which package groups you wish to install.\n")
#define NO_ROOT_TITLE _("No Root Device")
#define NO_ROOT_TEXT _("You must have at least one device marked for usage at mount path '/'.\n")
#define NO_SWAP_TITLE _("No Swap Device")
#define NO_SWAP_TEXT _("You have no devices marked for usage as 'swap'.\nIt is recommended that you have at least one.\nDo you wish to proceed without swap?\n")
#define NO_BASE_TITLE _("Group Selection Error")
#define NO_BASE_TEXT _("You must select at least the base package group.\n")
#define ROOT_TITLE _("Root Password Setup")
#define ROOT_TEXT _("Enter a password for the root user.\nIt must be at least 6 characters long.\n")
#define NAME_ENTRY_TEXT _("Real Name")
#define USER_ENTRY_TEXT _("User Name")
#define USER_TITLE _("Initial User Setup")
#define USER_TEXT _("Enter the information for an initial user.\nThe password must be at least 6 characters long.\n")
#define TIME_TITLE _("Initial Time Setup")
#define TIME_TEXT _("Select the timezone relevant to you from the list below.\n")
#define UTC_TEXT _("Universal Time Clock")
#define NO_USER_TITLE _("No User Name")
#define NO_USER_TEXT _("You must specify a user name.\n")

